feat: set up scaffholding
graasp/graasp-app-starter-lab pull request #2
Opened 2020-10-28 15:16 UTC by pyphilia

close #1

2020-11-04 13:46 UTC, juancarlosfarah commented
What does the purple button on the top left do?

2020-11-04 13:51 UTC, juancarlosfarah requested changes
Looks excellent! Just some very minor changes.

2020-11-04 13:51 UTC, juancarlosfarah commented on src/actions/layout.js
> +const toggleLoader = (showLoader) => (dispatch) =>
This is for the `ProgressScreen`, right? Maybe gets confused with the `Loader` component. Let's be consistent. I think renaming the component to `LoadingScreen` and then using `toggleLoadingScreen` and `showLoadingScreen` would be clearer.

2020-11-04 13:51 UTC, juancarlosfarah commented on src/components/App.js
> +      case MODES.STUDENT:
Love this.

2020-11-04 13:51 UTC, juancarlosfarah commented on src/components/common/Main.js
> +    zIndex: 999999,
Can we factor this out to a constant? Like `MAXIMUM_Z_INDEX` or something like that.

2020-11-04 13:51 UTC, juancarlosfarah commented on src/components/modes/teacher/TeacherView.js
> +    zIndex: 10000,
Can we factor this out like above? Not sure what to call it, though. `FAB_Z_INDEX`?

2020-11-04 13:51 UTC, juancarlosfarah commented on src/config/i18n.js
> +  fr: 'Français',
Very nice! I like this.

2020-11-05 12:01 UTC, hagoptaminian approved these changes
this looks good to me. I know we still have to build out `README.md` but might be worth already adding a note like:

_Once you clone the repository, to start the application correctly make sure to run `touch .env.local` and `echo "REACT_APP_BASE=" >> .env.local` in the project directory._

But of course could be done later in a README.md PR

2020-11-05 20:50 UTC, juancarlosfarah approved these changes

2020-11-06 10:19 UTC, pyphilia commented
I updated the readme with some steps to make the application run, and a tiny refactor for the buttons. I will merge it.

2020-11-06 10:20 UTC, merged